### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adamFinastra** [Baukebrenninkmeijer/table-evaluator#12]
It seems that all links to the documentation are down. Any chance to get a new link to access it?

**Comment by Baukebrenninkmeijer** [comment]
Oh, strange. Thanks for bringing it to my attention! I'll have a look asap.

**Comment by Baukebrenninkmeijer** [comment]
@adamFinastra Link is fixed :)

**Comment by adamFinastra** [comment]
Thank you!

Adam Lieberman
Data Scientist Lead

[signature_609878891]

FINASTRA  157 Technology Pkwy NW #100, Norcross, GA 30092

**Comment by Baukebrenninkmeijer** [comment]
Documentation is now also using a new theme and a bit more organised. Should be much nicer to look at! :)
