### ISSUE TITLE
[Feature Request] Supporting Pandas 1.0

### ISSUE THREAD

**Issue by hannahawalsh** [Baukebrenninkmeijer/table-evaluator#13]
I have a lot of code, much of which depends on pandas version > 1.0. When I install the package it downgrades my pandas. But then if I manually upgrade pandas back to 1.0.5, nothing with this package seems to break (yet). So it'd be great if we could have full pandas 1.0 support.

**Comment by Baukebrenninkmeijer** [comment]
Oeh, yeah good idea. I'll fix that asap!

**Comment by Baukebrenninkmeijer** [comment]
@hannahawalsh Are you sure it downgrades your pandas? In the requirements, it doesn't state a specific version and when I install it, it uses the latest pandas version by default (1.0.5). 

The only strict version is that of Dython, which in my testing does not create an issue here. Can you try again and let me know?

**Comment by hannahawalsh** [comment]
Okay so I tried doing it again and it didn't downgrade my pandas. I
installed/updates several other packages in the meantime so I'm wondering
if one of the dependencies of table-evaluator had the requirement of pandas
0.25 but it was telling me that table-evaluator had the dependency? Anyway,
feel free to close this because all works now
