### ISSUE TITLE
Suggestion: save generated images

### ISSUE THREAD

**Issue by Metalkiler** [Baukebrenninkmeijer/table-evaluator#14]
Hi there, and thanks for developing this package! It is very useful.

I was looking into the code and it could be useful to save the generated images for the disk (for instance if I have 3 gans generating data and want to compare which one are better)

For instance, I made a change on the distribution plot function and added that (save plot option)

What do you think?
I hope this suggestion helps 

Note: Don't known how to contribute to GitHub with forks yet 😂

**Comment by Baukebrenninkmeijer** [comment]
Hi @Metalkiler, nice suggestion. What do you think would be a good way? Create a directory and save all the image there? You can then pass a folder name, but the images have fixed names, since there's 3-4 images.

**Comment by Metalkiler** [comment]
I would suggest something like this :D 

table_evaluator.plot_distributions(nr_cols=4, nameplt="plots/image_at_epoch_"+str(i),title = "model "+ str(i)+ " KSTest: " + str(np.round(synthesizer.Ks[i],2)))

This way the person could personalize the models (these were the changes I made) xD

**Comment by Metalkiler** [comment]
And a option with showPlts = True if you wanted to see the printed plots after saving

**Comment by Metalkiler** [comment]
`    def plot_distributions(self, nr_cols=3, nameplt = "", extention = ".png", showPlot = False, title = ""):
        """
        Plot the distribution plots for all columns in the real and fake dataset. Height of each row of plots scales with the length of the labels. Each plot
        contains the values of a real columns and the corresponding fake column.
        """
        nr_charts = len(self.real.columns)
        nr_rows = max(1, nr_charts // nr_cols)
        nr_rows = nr_rows + 1 if nr_charts % nr_cols != 0 else nr_rows

        max_len = 0
        # Increase the length of plots if the labels are long
        if not self.real.select_dtypes(include=['object']).empty:
            lengths = []
            for d in self.real.select_dtypes(include=['object']):
                lengths.append(max([len(x.strip()) for x in self.real[d].unique().tolist()]))
            max_len = max(lengths)

        row_height = 6 + (max_len // 30)
        fig, ax = plt.subplots(nr_rows, nr_cols, figsize=(16, row_height * nr_rows))
        fig.suptitle(title, fontsize=16)
        axes = ax.flatten()
        for i, col in enumerate(self.real.columns):
            if col not in self.categorical_columns:
                try:
                    sns.distplot(self.real[col], ax=axes[i], label='Real')
                    sns.distplot(self.fake[col], ax=axes[i], color='darkorange', label='Fake')
                except RuntimeError:
                    axes[i].clear()
                    sns.distplot(self.real[col], ax=axes[i], label='Real', kde=False)
                    sns.distplot(self.fake[col], ax=axes[i], color='darkorange', label='Fake', kde=False)
                axes[i].set_autoscaley_on(True)
                axes[i].legend()
            else:
                real = self.real.copy()
                fake = self.fake.copy()
                real['kind'] = 'Real'
                fake['kind'] = 'Fake'
                concat = pd.concat([fake, real])
                palette = sns.color_palette(
                    [(0.8666666666666667, 0.5176470588235295, 0.3215686274509804),
                     (0.2980392156862745, 0.4470588235294118, 0.6901960784313725)])
                x, y, hue = col, "proportion", "kind"
                ax = (concat[x]
                      .groupby(concat[hue])
                      .value_counts(normalize=True)
                      .rename(y)
                      .reset_index()
                      .pipe((sns.barplot, "data"), x=x, y=y, hue=hue, ax=axes[i], saturation=0.8, palette=palette))
                ax.set_xticklabels(axes[i].get_xticklabels(), rotation='vertical')
        plt.tight_layout(rect=[0, 0.02, 1, 0.98])
        nameplts = nameplt+extention
        plt.savefig(nameplts.replace(" ",""))
        if showPlot:
            plt.show()`

**Comment by Metalkiler** [comment]
` nameplts = nameplt+extention
        plt.savefig(nameplts.replace(" ",""))
        if showPlot:
            plt.show()
`

**Comment by Zepp3** [comment]
Hi!

Is this feature to save the plots already added?

Kind regards!

**Comment by Baukebrenninkmeijer** [comment]
@Zepp3 I'm afraid not. I haven't really spend time on this library recently. Feel free to create a PR if you feel comfortable. Since the images are grouped per section, saving all images of a run should only be 4 clicks, if you need this functionality in the meantime.

**Comment by Zepp3** [comment]
Yeah, you're right. In the meantime, I just can save the plots manually. If I find the time I'll try to automize it in the source code, thanks.
