### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by glederrey** [Baukebrenninkmeijer/table-evaluator#17]
Dear Bauke, 

First of all, I'd like to congratulate and thank you for your work. I've read your master thesis and found it really useful in my case! I'm currently using your table evaluator to complete the assessment of the synthetic data I'm generating. However, I have a small issue and I'm not sure why it's the case. 

When I compute results on two similar datasets, with my methods, I get similar results. However, when I use your method, I can get this:

This one looks good
```
Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index                                                                    
LogisticRegression_real_testset       0.7620   0.7531              0.9208
LogisticRegression_fake_testset       0.7229   0.7283              0.8966
RandomForestClassifier_real_testset   0.8755   0.7432              0.6826
RandomForestClassifier_fake_testset   0.7034   0.7359              0.7204
DecisionTreeClassifier_real_testset   0.8220   0.6257              0.4483
DecisionTreeClassifier_fake_testset   0.6115   0.6349              0.4268
MLPClassifier_real_testset            0.7998   0.7365              0.7001
MLPClassifier_fake_testset            0.6769   0.7431              0.6339

Miscellaneous results:
                                           Result
Column Correlation Distance RMSE           0.0205
Column Correlation distance MAE            0.0128
Duplicate rows between sets (real/fake)  (385, 0)
nearest neighbor mean                      1.9832
nearest neighbor std                       0.4723

Results:
                                                Result
Basic statistics                                1.0000
Correlation column correlations                 0.9917
Mean Correlation between fake and real columns  0.9317
1 - MAPE Estimator results                      0.9161
Similarity Score                                0.9599
```
This one looks bad (especially `f1_fake` and `1 - MAPE Estimator results`)
```
Correlation metric: pearsonr

Classifier F1-scores and their Jaccard similarities:
                                     f1_real  f1_fake  jaccard_similarity
index                                                                    
LogisticRegression_real_testset       0.7583   0.2177              0.0757
LogisticRegression_fake_testset       0.1813   0.7179              0.0387
RandomForestClassifier_real_testset   0.8758   0.3559              0.2154
RandomForestClassifier_fake_testset   0.2134   0.7150              0.0899
DecisionTreeClassifier_real_testset   0.8253   0.3064              0.1811
DecisionTreeClassifier_fake_testset   0.1723   0.6086              0.0997
MLPClassifier_real_testset            0.7954   0.3255              0.1856
MLPClassifier_fake_testset            0.2405   0.7263              0.1094

Miscellaneous results:
                                           Result
Column Correlation Distance RMSE           0.0191
Column Correlation distance MAE            0.0118
Duplicate rows between sets (real/fake)  (385, 0)
nearest neighbor mean                      2.2004
nearest neighbor std                       0.3976

Results:
                                                Result
Basic statistics                                1.0000
Correlation column correlations                 0.9946
Mean Correlation between fake and real columns  0.9225
1 - MAPE Estimator results                     -0.5485
Similarity Score                                0.5922
```
My question is the following:
- Where do you think this could come from? Is it from the sampling? Or there's a problem with my datasets? (other metrics really indicates that they are quite similar)
- Did you have similar issues while you were testing your different models? 

Second, unrelated, question:
- Why did you remove the PCA similarity score from the table evaluation while it's given in your thesis? Is there something wrong with it?

Thanks in advance for your help!

**Comment by Baukebrenninkmeijer** [comment]
Hi @glederrey, glad you like it! Great to hear that people are still using it. :)

Regarding your questions, I tried to remove as much randomness from the code as possible, but the train/test split is still 	random since it seems i'm not passing the random state. I think this slipped my mind at the time of writing. Presumable, fixing the random state of the train/test split should improve the results a bit. 

Alternatively, if you have passed the `n_samples` parameter to the class, it will sample the data randomly. This is also not fixed to a specific seed at the moment. 

If you like, a PR with these changes would be greatly appreciated. Otherwise I might have a look sometime in the future.

**Comment by glederrey** [comment]
Hi @Baukebrenninkmeijer,

I've played a bit with your code and I changed some stuff to make sure it works. In the end, the issue was mainly coming from the numerical encoding. (I also added cross-validation for the Machine Learning efficacy metrics)

I will do a PR as soon as I find a bit of time. (Maybe next week)
