### ISSUE TITLE
cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by LastMinuteHero** [Baukebrenninkmeijer/table-evaluator#22]
Hey I've been trying to use your table-evaluator, yet I keep getting the error, that I cannot reindex from a duplicate axis.
After fiddeling around with my datasets, I've decided to try it with your example code/dataset and I get the same error message.
I've also tried it now on different machines but with no positive results.

Any clue what I'm doing wrong here?

Thanks!

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16524/1726253940.py in <module>
----> 1 evaluator.visual_evaluation()

~\Documents\Untitled Folder\table-evaluator-master\table_evaluator\table_evaluator.py in visual_evaluation(self, save_dir, **kwargs)
    374             self.plot_mean_std()
    375             self.plot_cumsums()
--> 376             self.plot_distributions()
    377             self.plot_correlation_difference(**kwargs)
    378             self.plot_pca()

~\Documents\Untitled Folder\table-evaluator-master\table_evaluator\table_evaluator.py in plot_distributions(self, nr_cols, fname)
    155             if col not in self.categorical_columns:
    156                 plot_df = pd.DataFrame({col: self.real[col].append(self.fake[col]), 'kind': ['real'] * self.n_samples + ['fake'] * self.n_samples})
--> 157                 fig = sns.histplot(plot_df, x=col, hue='kind', ax=axes[i], stat='probability', legend=True)
    158                 axes[i].set_autoscaley_on(True)
    159             else:

~\Anaconda3\lib\site-packages\seaborn\distributions.py in histplot(data, x, y, hue, weights, stat, bins, binwidth, binrange, discrete, cumulative, common_bins, common_norm, multiple, element, fill, shrink, kde, kde_kws, line_kws, thresh, pthresh, pmax, cbar, cbar_ax, cbar_kws, palette, hue_order, hue_norm, color, log_scale, legend, ax, **kwargs)
   1460     if p.univariate:
   1461 
-> 1462         p.plot_univariate_histogram(
   1463             multiple=multiple,
   1464             element=element,

~\Anaconda3\lib\site-packages\seaborn\distributions.py in plot_univariate_histogram(self, multiple, element, fill, common_norm, common_bins, shrink, kde, kde_kws, color, legend, line_kws, estimate_kws, **plot_kws)
    398         if set(self.variables) - {"x", "y"}:
    399 
--> 400             all_data = self.comp_data.dropna()
    401 
    402             if common_bins:

~\Anaconda3\lib\site-packages\seaborn\_core.py in comp_data(self)
   1055                     orig = self.plot_data[var].dropna()
   1056                 comp_col = pd.Series(index=orig.index, dtype=float, name=var)
-> 1057                 comp_col.loc[orig.index] = pd.to_numeric(axis.convert_units(orig))
   1058 
   1059                 if axis.get_scale() == "log":

~\Anaconda3\lib\site-packages\pandas\core\indexing.py in __setitem__(self, key, value)
    668 
    669         iloc = self if self.name == "iloc" else self.obj.iloc
--> 670         iloc._setitem_with_indexer(indexer, value)
    671 
    672     def _validate_key(self, key, axis: int):

~\Anaconda3\lib\site-packages\pandas\core\indexing.py in _setitem_with_indexer(self, indexer, value)
   1788                 # setting for extensionarrays that store dicts. Need to decide
   1789                 # if it's worth supporting that.
-> 1790                 value = self._align_series(indexer, Series(value))
   1791 
   1792             elif isinstance(value, ABCDataFrame):

~\Anaconda3\lib\site-packages\pandas\core\indexing.py in _align_series(self, indexer, ser, multiindex_indexer)
   1907             # series, so need to broadcast (see GH5206)
   1908             if sum_aligners == self.ndim and all(is_sequence(_) for _ in indexer):
-> 1909                 ser = ser.reindex(obj.axes[0][indexer[0]], copy=True)._values
   1910 
   1911                 # single indexer

~\Anaconda3\lib\site-packages\pandas\core\series.py in reindex(self, index, **kwargs)
   4409     )
   4410     def reindex(self, index=None, **kwargs):
-> 4411         return super().reindex(index=index, **kwargs)
   4412 
   4413     def drop(

~\Anaconda3\lib\site-packages\pandas\core\generic.py in reindex(self, *args, **kwargs)
   4459 
   4460         # perform the reindex on the axes
-> 4461         return self._reindex_axes(
   4462             axes, level, limit, tolerance, method, fill_value, copy
   4463         ).__finalize__(self, method="reindex")

~\Anaconda3\lib\site-packages\pandas\core\generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4479 
   4480             axis = self._get_axis_number(a)
-> 4481             obj = obj._reindex_with_indexers(
   4482                 {axis: [new_index, indexer]},
   4483                 fill_value=fill_value,

~\Anaconda3\lib\site-packages\pandas\core\generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   4522 
   4523             # TODO: speed up on homogeneous DataFrame objects
-> 4524             new_data = new_data.reindex_indexer(
   4525                 index,
   4526                 indexer,

~\Anaconda3\lib\site-packages\pandas\core\internals\managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, consolidate)
   1274         # some axes don't allow reindexing with dups
   1275         if not allow_dups:
-> 1276             self.axes[axis]._can_reindex(indexer)
   1277 
   1278         if axis >= self.ndim:

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in _can_reindex(self, indexer)
   3287         # trying to reindex on an axis with duplicates
   3288         if not self.is_unique and len(indexer):
-> 3289             raise ValueError("cannot reindex from a duplicate axis")
   3290 
   3291     def reindex(self, target, method=None, level=None, limit=None, tolerance=None):

ValueError: cannot reindex from a duplicate axis

**Comment by Zepp3** [comment]
Hi! Did you already found a solution to this problem? 
Kind regards!

**Comment by Zepp3** [comment]
Try downgrading to seaborn==0.11.1, that might help. There are some issues with the newest seaborn version and pandas...

**Comment by LastMinuteHero** [comment]
Thanks man, that was it!!
Works fine now.
Wish you wonderful holidays and a great start into 2022! :)

**Comment by Zepp3** [comment]
Nice! Thanks, you too!

**Comment by vipul5247** [comment]
Alternatively, one can also reindex the fake data from any arbitrary value more than the index of real data so that there is no overlap.
`max_index = real_data.index.max()
fake_data.index = range(max_index+1,num_samples+max_index+1,1)`

**Comment by Baukebrenninkmeijer** [comment]
Oh, that's unfortunate. I'll check on the dependencies and might fix the seaborn version in this case. Thanks for the help @Zepp3  and @vipul5247!

Closing since it seems to be resolved.
