### ISSUE TITLE
Enhancement: select the desired visual evaluation

### ISSUE THREAD

**Issue by Zepp3** [Baukebrenninkmeijer/table-evaluator#24]
Hi,

some suggestions to make the module maybe even better: it would be nice to select which visual evaluation one wants to plot. The advancement would be for example that for high-dimensional data, one could dispense e.g. the cumulative sum plots, which would probably error out in most displaying methods (like in a jupyter notebook).

**Comment by Baukebrenninkmeijer** [comment]
Hi @Zepp3, all the underlying functions are available in the package, so you can select specific ones there. I don't immediately see added value of being able to select them from the `.visual_evaluation()` method directly.
