### ISSUE TITLE
FixedLocator locations issue

### ISSUE THREAD

**Issue by hawkiyc** [Baukebrenninkmeijer/table-evaluator#33]
Hi, I keep getting the following error while comparing forged data by CTGAN and the real one.

Here is the error message I got:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-8b4ec6283de6> in <cell line: 13>()
     11 table_evaluator =  TableEvaluator(real, fake, cat_cols= categorical_features)
     12 
---> 13 table_evaluator.visual_evaluation()

5 frames
/usr/local/lib/python3.10/dist-packages/table_evaluator/table_evaluator.py in visual_evaluation(self, save_dir, **kwargs)
    373         if save_dir is None:
    374             self.plot_mean_std()
--> 375             self.plot_cumsums()
    376             self.plot_distributions()
    377             self.plot_correlation_difference(**kwargs)

/usr/local/lib/python3.10/dist-packages/table_evaluator/table_evaluator.py in plot_cumsums(self, nr_cols, fname)
    122             r = self.real[col]
    123             f = self.fake.iloc[:, self.real.columns.tolist().index(col)]
--> 124             cdf(r, f, col, 'Cumsum', ax=axes[i])
    125         plt.tight_layout(rect=[0, 0.02, 1, 0.98])
    126 

/usr/local/lib/python3.10/dist-packages/table_evaluator/viz.py in cdf(data_r, data_f, xlabel, ylabel, ax)
    170         ticks_loc = ax.get_xticks()
    171         ax.xaxis.set_major_locator(mticker.FixedLocator(ticks_loc))
--> 172         ax.set_xticklabels(data_r.sort_values().unique(), rotation='vertical')
    173 
    174     if ax is None:

/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_base.py in wrapper(self, *args, **kwargs)
     73 
     74         def wrapper(self, *args, **kwargs):
---> 75             return get_method(self)(*args, **kwargs)
     76 
     77         wrapper.__module__ = owner.__module__

/usr/local/lib/python3.10/dist-packages/matplotlib/axis.py in _set_ticklabels(self, labels, fontdict, minor, **kwargs)
   1796         if fontdict is not None:
   1797             kwargs.update(fontdict)
-> 1798         return self.set_ticklabels(labels, minor=minor, **kwargs)
   1799 
   1800     def _set_tick_locations(self, ticks, *, minor=False):

/usr/local/lib/python3.10/dist-packages/matplotlib/axis.py in set_ticklabels(self, ticklabels, minor, **kwargs)
   1718             # remove all tick labels, so only error for > 0 ticklabels
   1719             if len(locator.locs) != len(ticklabels) and len(ticklabels) != 0:
-> 1720                 raise ValueError(
   1721                     "The number of FixedLocator locations"
   1722                     f" ({len(locator.locs)}), usually from a call to"

ValueError: The number of FixedLocator locations (290), usually from a call to set_ticks, does not match the number of ticklabels (275).
```
I tried to downgrade table-evaluator, and this message keeps popping out until ver 1.2.2.post1. However, `TypeError: Image data of dtype object cannot be converted to float` showed up.

I also tested downgrade matplotlib, and this way isn't working either.

Here is my code and csv files on [google colab](https://drive.google.com/drive/folders/1gIRuRaSmgLEw7aQlyuf7cYy7eLh-Cujw?usp=share_link)

**Comment by Baukebrenninkmeijer** [comment]
@hawkiyc I'll have a look as soon as I have time. Apologies for the delayed response.

**Comment by Baukebrenninkmeijer** [comment]
@hawkiyc Fix is ready for merge in #34. Will soon merge and deploy.

**Comment by Baukebrenninkmeijer** [comment]
@hawkiyc Please update and check. Issue should be resolved! :)

Also thanks for using the package and reporting the issue!

**Comment by hawkiyc** [comment]
@Baukebrenninkmeijer It's working now, thank you very much.

Yet there is a slight issue; the previous version can draw the kde curve on the histogram as the following chart.

![image](https://github.com/Baukebrenninkmeijer/table-evaluator/assets/76748651/27b93510-b736-4faa-a9cf-0617231886b8)
Chart from this tutorial: [Tabular Synthetic Data Generation using CTGAN](https://www.maskaravivek.com/post/ctgan-tabular-synthetic-data-generation/)

And there is no kde curve in this version.

![image](https://github.com/Baukebrenninkmeijer/table-evaluator/assets/76748651/96e466f6-44c5-4661-a277-6126bfb3c3c1)

For now, I solved this issue by adding `kde=True` at line 164 in table_evaluator.py on my device. However, users running table_evalutor on cloud env, such as Google colab, can't have the kde curve by modifying the source code.

For those running code on cloud env, having the KDE curve on the histogram will be great. Hence, I'd like to request a favor in modifying your library again for a better user experience.

**Comment by Baukebrenninkmeijer** [comment]
@hawkiyc  I see, seems to have been removed as default by seaborn at some time. Enabled now again. Let me publish and check it out.

**Comment by Baukebrenninkmeijer** [comment]
@hawkiyc Should be fixed. Let me know! They changed the shading but the lines are there, so it should be fine.

**Comment by hawkiyc** [comment]
@Baukebrenninkmeijer It works perfectly. Thank you very much for your time.
